# Generated by Django 5.1.1 on 2024-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('empId', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=30)),
                ('empSal', models.IntegerField(max_length=30)),
            ],
        ),
    ]
